// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dsgpjivqwadssuqbibdk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzZ3BqaXZxd2Fkc3N1cWJpYmRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2OTExMDEsImV4cCI6MjA2MTI2NzEwMX0.QgjY4sM4eL-5maVJMTTfozuQqKiJ_FAIY1npEFlOsa8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);